function trans = rotx(theta,axis,use_4by4)

if (nargin < 2), axis = 1; end % default is rotate about X
if (nargin < 3), use_4by4 = 0; end % default is generate only 3x3 Euler

% compute coefs
cot = cos(theta);
sit = sin(theta);

% create transformation
switch axis
    case 1
    trans = [...
        1 0 0 0;...
        0 cot -sit 0;...
        0 sit cot 0;...
        0 0 0 1];
    
    case 2    
    trans = [...
        cot  0  sit  0;...
        0    1    0  0;...
        -sit 0  cot  0;...
        0    0    0  1];
    
    case 3
    trans = [...
        cot -sit 0 0;...
        sit  cot 0 0;...
        0 0 1 0;...
        0 0 0 1];
end

if (~use_4by4)
    trans = trans(1:3,1:3);
end
return
